/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.settings;

import java.awt.Dimension;
import java.awt.Toolkit;
import settings.GeneralSettings;
import static settings.GeneralSettings.*;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import view.main.MainWindow;

/**
 *
 * @author christiancolbach
 */
public class AdvancedSettingsWindow extends javax.swing.JFrame {

    private final GeneralSettings settings;
    private final MainWindow main;
    
    /**
     * Creates new form SettingsWindow
     */
    public AdvancedSettingsWindow(MainWindow main) {
        initComponents();
        this.settings = GeneralSettings.getInstance();
        this.advancedTestingCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_ADVANCED_TESTING_KEY, false));
        this.redrawCounterCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_REDRAW_COUNTER_KEY, false));
        this.logRedrawCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_LOG_REDRAW_KEY, false));
        this.targetCoordinatesCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_TARGET_COORDINATES_KEY, false));
        this.mouseCoordinatesCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_MOUSE_COORDINATES_KEY, false));
        this.logToFileCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_LOG_TO_FILE_KEY, false));
        this.logMoreCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_LOG_MORE_KEY, false));
        this.logOnlyErrorsToFileCheckBox.setEnabled(logToFileCheckBox.isSelected());
        this.nodeCountCheckBox.setSelected(this.settings.getBoolean(DEVELOPER_NODE_COUNT_KEY, false));
        this.main = main;
        
        // Fenster mittig plazieren...
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        redrawCounterCheckBox = new javax.swing.JCheckBox();
        logRedrawCheckBox = new javax.swing.JCheckBox();
        targetCoordinatesCheckBox = new javax.swing.JCheckBox();
        logToFileCheckBox = new javax.swing.JCheckBox();
        logOnlyErrorsToFileCheckBox = new javax.swing.JCheckBox();
        logMoreCheckBox = new javax.swing.JCheckBox();
        mouseCoordinatesCheckBox = new javax.swing.JCheckBox();
        nodeCountCheckBox = new javax.swing.JCheckBox();
        advancedTestingCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Erweitert");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Entwickler:");

        redrawCounterCheckBox.setText("Redraw Counter");
        redrawCounterCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redrawCounterCheckBoxActionPerformed(evt);
            }
        });

        logRedrawCheckBox.setText("Redraw loggen");

        targetCoordinatesCheckBox.setText("Ziel Koordinaten anzeigen");

        logToFileCheckBox.setText("Ausgaben in Datei speichern");
        logToFileCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logToFileCheckBoxActionPerformed(evt);
            }
        });

        logOnlyErrorsToFileCheckBox.setText("Nur Fehler in Datei speichern");

        logMoreCheckBox.setText("Mehr Ausgaben");

        mouseCoordinatesCheckBox.setText("Maus Koordinaten anzeigen");

        nodeCountCheckBox.setText("Anzahl Elemente anzeigen");

        advancedTestingCheckBox.setText("Funktionen zum erweiterten Testen");
        advancedTestingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedTestingCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(redrawCounterCheckBox)
                    .addComponent(logOnlyErrorsToFileCheckBox)
                    .addComponent(logMoreCheckBox)
                    .addComponent(logRedrawCheckBox)
                    .addComponent(logToFileCheckBox)
                    .addComponent(mouseCoordinatesCheckBox)
                    .addComponent(nodeCountCheckBox)
                    .addComponent(targetCoordinatesCheckBox)
                    .addComponent(advancedTestingCheckBox))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advancedTestingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redrawCounterCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logRedrawCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(targetCoordinatesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mouseCoordinatesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logToFileCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logOnlyErrorsToFileCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logMoreCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nodeCountCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            settings.set(DEVELOPER_ADVANCED_TESTING_KEY, advancedTestingCheckBox.isSelected());
            settings.set(DEVELOPER_REDRAW_COUNTER_KEY, redrawCounterCheckBox.isSelected());
            settings.set(DEVELOPER_LOG_REDRAW_KEY, logRedrawCheckBox.isSelected());
            settings.set(DEVELOPER_TARGET_COORDINATES_KEY, targetCoordinatesCheckBox.isSelected());
            settings.set(DEVELOPER_MOUSE_COORDINATES_KEY, mouseCoordinatesCheckBox.isSelected());
            settings.set(DEVELOPER_LOG_TO_FILE_KEY, logToFileCheckBox.isSelected());
            settings.set(DEVELOPER_LOG_ONLY_ERRORS_TO_FILE_KEY, logOnlyErrorsToFileCheckBox.isSelected());
            settings.set(DEVELOPER_LOG_MORE_KEY, logMoreCheckBox.isSelected());
            settings.set(DEVELOPER_NODE_COUNT_KEY, nodeCountCheckBox.isSelected());
            settings.writeSettingsToSettingsFile();
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Schreiben in Datei fehlgeschlagen! (" + ex.getLocalizedMessage() + ")", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void redrawCounterCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redrawCounterCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redrawCounterCheckBoxActionPerformed

    private void logToFileCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logToFileCheckBoxActionPerformed
        logOnlyErrorsToFileCheckBox.setEnabled(logToFileCheckBox.isSelected());
    }//GEN-LAST:event_logToFileCheckBoxActionPerformed

    private void advancedTestingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedTestingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_advancedTestingCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox advancedTestingCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox logMoreCheckBox;
    private javax.swing.JCheckBox logOnlyErrorsToFileCheckBox;
    private javax.swing.JCheckBox logRedrawCheckBox;
    private javax.swing.JCheckBox logToFileCheckBox;
    private javax.swing.JCheckBox mouseCoordinatesCheckBox;
    private javax.swing.JCheckBox nodeCountCheckBox;
    private javax.swing.JCheckBox redrawCounterCheckBox;
    private javax.swing.JCheckBox targetCoordinatesCheckBox;
    // End of variables declaration//GEN-END:variables
}
