/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.settings;

import java.awt.Dimension;
import java.awt.Toolkit;
import settings.GeneralSettings;
import static settings.GeneralSettings.*;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import view.main.MainWindow;

/**
 *
 * @author christiancolbach
 */
public class SettingsWindow extends javax.swing.JFrame {

    private final GeneralSettings settings;
    private final MainWindow main;
    
    /**
     * Creates new form SettingsWindow
     */
    public SettingsWindow(MainWindow main) {
        initComponents();
        this.main = main;
        this.settings = GeneralSettings.getInstance();
        this.viewAdditionalHelpCheckBox.setSelected(this.settings.getBoolean(VIEW_ADDITIONAL_HELP_KEY, true));
        String backgroundValue = settings.getString(VIEW_BACKGROUND_KEY, VIEW_BACKGROUND_VALUE_DEFAULT);
        if(backgroundValue.trim().equalsIgnoreCase(VIEW_BACKGROUND_VALUE_DEFAULT))
            backgroundDefaultRadioButton.setSelected(true);
        else {
            backgroundBlueprintRadioButton.setSelected(true);
        }
        
        // Fenster mittig plazieren...
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - getSize().width / 2, dim.height / 2 - getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewAdditionalHelpCheckBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backgroundDefaultRadioButton = new javax.swing.JRadioButton();
        backgroundBlueprintRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Einstellungen");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hilfe:");

        viewAdditionalHelpCheckBox.setText("Zusätzliche Hilfe einblenden (unten rechts)");

        jButton2.setText("Erweitert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Hintergrund:");

        backgroundButtonGroup.add(backgroundDefaultRadioButton);
        backgroundDefaultRadioButton.setText("Standard");
        backgroundDefaultRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundDefaultRadioButtonActionPerformed(evt);
            }
        });

        backgroundButtonGroup.add(backgroundBlueprintRadioButton);
        backgroundBlueprintRadioButton.setText("Blueprint");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(viewAdditionalHelpCheckBox)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backgroundDefaultRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backgroundBlueprintRadioButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAdditionalHelpCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundDefaultRadioButton)
                    .addComponent(backgroundBlueprintRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            settings.set(VIEW_ADDITIONAL_HELP_KEY, viewAdditionalHelpCheckBox.isSelected());
            if(backgroundDefaultRadioButton.isSelected()) {
                settings.set(VIEW_BACKGROUND_KEY, VIEW_BACKGROUND_VALUE_DEFAULT);
            } else if(backgroundBlueprintRadioButton.isSelected()) {
                settings.set(VIEW_BACKGROUND_KEY, VIEW_BACKGROUND_VALUE_BLUEPRINT);
            }
            settings.writeSettingsToSettingsFile();
            main.repaint();
            dispose();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Schreiben in Datei fehlgeschlagen! (" + ex.getLocalizedMessage() + ")", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        main.openAdvancedSettingsWindow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backgroundDefaultRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundDefaultRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundDefaultRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton backgroundBlueprintRadioButton;
    private javax.swing.ButtonGroup backgroundButtonGroup;
    private javax.swing.JRadioButton backgroundDefaultRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox viewAdditionalHelpCheckBox;
    // End of variables declaration//GEN-END:variables
}
