package view.onrun.shownumberarray;

import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import logging.AdditionalOut;
import reflection.SmartIdentifier;
import utils.images.ImageSaving;
import view.listener.InputManager;
import view.onrun.DragAreaListener;
import view.onrun.ShowSomethingWindow;
import view.onrun.UnsupportedShowTypeException;

public class ShowNumberArrayWindow extends ShowSomethingWindow {

    private Number[] numbers = null;
    private boolean closed = false;
    
    public ShowNumberArrayWindow(Number[] numbers, SmartIdentifier smartIdentifier) {
        initComponents();
        setNumbers(numbers);
        setTitle(smartIdentifier.getIdentifierName());
    }
    
    /**
     * Setzt Bitmap und aktualisiert abhaengige View.
     */
    public final void setNumbers(Number[] numbers) {
        if(numbers != null && this.numbers != numbers) {
            this.numbers = numbers;
            showNumberArrayPanel.setNumbers(numbers);
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayGroup = new javax.swing.ButtonGroup();
        showNumberArrayPanel = new view.onrun.shownumberarray.ShowNumberArrayPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        showNumberArrayPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showNumberArrayPanelMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                showNumberArrayPanelMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout showNumberArrayPanelLayout = new javax.swing.GroupLayout(showNumberArrayPanel);
        showNumberArrayPanel.setLayout(showNumberArrayPanelLayout);
        showNumberArrayPanelLayout.setHorizontalGroup(
            showNumberArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        showNumberArrayPanelLayout.setVerticalGroup(
            showNumberArrayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Als Datei speichern");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Anschicht");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, 0));
        displayGroup.add(jRadioButtonMenuItem1);
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Kurve");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        displayGroup.add(jRadioButtonMenuItem2);
        jRadioButtonMenuItem2.setText("Blöcke");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showNumberArrayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showNumberArrayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        closed = true;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        closed = true;
    }//GEN-LAST:event_formWindowClosing

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        //ImageSaving.saveImageToFileViaDialog(numb, this, ".");
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        showNumberArrayPanel.setCurve(false);
        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        showNumberArrayPanel.setCurve(true);
        repaint();
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void showNumberArrayPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showNumberArrayPanelMouseMoved
        showNumberArrayPanel.setMouseX(evt.getX());
        showNumberArrayPanel.setMouseY(evt.getY());
        repaint();
    }//GEN-LAST:event_showNumberArrayPanelMouseMoved

    private void showNumberArrayPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showNumberArrayPanelMouseDragged
        showNumberArrayPanel.setMouseX(evt.getX());
        showNumberArrayPanel.setMouseY(evt.getY());
        repaint();
    }//GEN-LAST:event_showNumberArrayPanelMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup displayGroup;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JMenuItem saveMenuItem;
    private view.onrun.shownumberarray.ShowNumberArrayPanel showNumberArrayPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean canShow(Object o) {
        return o instanceof Number[];
    }

    @Override
    public void show(Object o) throws UnsupportedShowTypeException {
        if(o instanceof Number[]) {
            setNumbers((Number[]) o);
        } else {
            throw new UnsupportedShowTypeException(o.getClass());
        }
    }

    @Override
    public boolean isClosed() {
        return closed;
    }
}
