package view.main.runreport;

import logging.AdditionalOut;
import java.awt.event.MouseEvent;
import logging.AdditionalLogger;
import model.*;
import model.runproject.*;
import model.runproject.debugger.*;
import model.runproject.report.*;
import view.listener.*;

public class RunReportWindow extends javax.swing.JFrame {

    private final Report report;
    private final InputManager inputManager;
    
    /**
     * Creates new form NodeInfoWindow
     */
    public RunReportWindow(Report report) {
        this.inputManager = new InputManager();
        this.report = report;
        this.initComponents();
        this.generalRuntimePanel.setReport(report);
        this.runtimeChartPanel.setChartData(report);
        this.logPanel.setWhiteMode(true);
        this.logPanel.setSource(report.getOutput());
        this.inputManager.addListener(logPanel.getScrollbar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalRuntimePanel = new view.main.runreport.GeneralRuntimePanel();
        runtimeChartPanel = new view.main.runreport.RuntimeChartPanel();
        logPanel = new view.sharedcomponents.LogPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bericht");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout generalRuntimePanelLayout = new javax.swing.GroupLayout(generalRuntimePanel);
        generalRuntimePanel.setLayout(generalRuntimePanelLayout);
        generalRuntimePanelLayout.setHorizontalGroup(
            generalRuntimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        generalRuntimePanelLayout.setVerticalGroup(
            generalRuntimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout runtimeChartPanelLayout = new javax.swing.GroupLayout(runtimeChartPanel);
        runtimeChartPanel.setLayout(runtimeChartPanelLayout);
        runtimeChartPanelLayout.setHorizontalGroup(
            runtimeChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        runtimeChartPanelLayout.setVerticalGroup(
            runtimeChartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        logPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                logPanelMouseDragged(evt);
            }
        });
        logPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                logPanelMouseWheelMoved(evt);
            }
        });
        logPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logPanelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout logPanelLayout = new javax.swing.GroupLayout(logPanel);
        logPanel.setLayout(logPanelLayout);
        logPanelLayout.setHorizontalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        logPanelLayout.setVerticalGroup(
            logPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jLabel1.setText("Meldungen:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(generalRuntimePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runtimeChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(generalRuntimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(runtimeChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        AdditionalLogger.out.println("Scrollbar-Area von LogPanel wird aktualisiert");
        logPanel.updateScrollbarArea();
    }//GEN-LAST:event_formComponentResized

    private void logPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logPanelMousePressed
        inputManager.mousePressed(evt.getX(), evt.getY(), evt.getButton() == MouseEvent.BUTTON1);
        repaint();
    }//GEN-LAST:event_logPanelMousePressed

    private void logPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logPanelMouseReleased
        inputManager.mouseReleased(evt.getX(), evt.getY());
        repaint();
    }//GEN-LAST:event_logPanelMouseReleased

    private void logPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_logPanelMouseWheelMoved
        inputManager.mouseMouseWheelMoved(evt.getUnitsToScroll());
        repaint();
    }//GEN-LAST:event_logPanelMouseWheelMoved

    private void logPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logPanelMouseDragged
        inputManager.mouseDragged(evt.getX(), evt.getY());
        repaint();
    }//GEN-LAST:event_logPanelMouseDragged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.main.runreport.GeneralRuntimePanel generalRuntimePanel;
    private javax.swing.JLabel jLabel1;
    private view.sharedcomponents.LogPanel logPanel;
    private view.main.runreport.RuntimeChartPanel runtimeChartPanel;
    // End of variables declaration//GEN-END:variables
}
